### ISSUE TITLE
Next/Previous links in sphinx sidebar

### ISSUE THREAD

**Issue by ghost** [uthcode/learntosolveit#101]
Is there any way to put sphinx's usual "next" and "previous" in the sidebar? That way once you finish one exercise it's easy to move onto the next. 

At the moment you need to go back, find where you were up to and then go into the exercise. This seems quite unnecessary when most of the exercises are designed toi be done sequentially and gets annoying once you've done a couple.

The attached screenshot shows these links on the operator page of python's official docs to demonstrate what I mean.

![imgur-2016_02_05-15 41 12](https://cloud.githubusercontent.com/assets/12974869/12840517/06fa6a12-cc1f-11e5-8e05-69df9a905f5d.png)

**Comment by orsenthil** [comment]
@AnonRandom , I will investigate the provision of this.

**Comment by orsenthil** [comment]
For the theme, I use for the site, this was not really suitable.

Closing this as won't fix.

**Comment by orsenthil** [comment]
Actually, I think, I will modify the theme to handle this better. It will improve the experience.

**Comment by orsenthil** [comment]
This is the way to accomplish this - http://stackoverflow.com/questions/26260726/how-do-i-add-a-previous-chapter-and-next-chapter-link-in-documentation-gener

**Comment by orsenthil** [comment]
I have changed the theme which has next and previous links.
